// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ7mNuk0dc5QPl280ySVOyUZWiTF50QUk',
    appId: '1:843040157256:web:d3f20901479a44f0e6727d',
    messagingSenderId: '843040157256',
    projectId: 'engezha-app',
    authDomain: 'engezha-app.firebaseapp.com',
    storageBucket: 'engezha-app.firebasestorage.app',
    measurementId: 'G-M601RRK8LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAasX4iZWkX-B2W8LGIXxVJS711MXg4y2E',
    appId: '1:843040157256:android:92976d986a71beade6727d',
    messagingSenderId: '843040157256',
    projectId: 'engezha-app',
    storageBucket: 'engezha-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6pBt_Rkn9EmYf4e0GnwKpLzTRGQM2u0U',
    appId: '1:843040157256:ios:97906a3bbf7342fde6727d',
    messagingSenderId: '843040157256',
    projectId: 'engezha-app',
    storageBucket: 'engezha-app.firebasestorage.app',
    iosBundleId: 'com.example.engezzzha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ7mNuk0dc5QPl280ySVOyUZWiTF50QUk',
    appId: '1:843040157256:web:636426d59e48f55ce6727d',
    messagingSenderId: '843040157256',
    projectId: 'engezha-app',
    authDomain: 'engezha-app.firebaseapp.com',
    storageBucket: 'engezha-app.firebasestorage.app',
    measurementId: 'G-4KYQX5RGH2',
  );
}
